ALTER TABLE [dbo].[PART]
DROP COLUMN COMP_ID;

CREATE TABLE BUILD (
COMP_ID INT NOT NULL,
PART_ID INT NOT NULL,
PRIMARY KEY (COMP_ID, PART_ID),
FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID),
FOREIGN KEY (COMP_ID) REFERENCES COMPONENT(COMP_ID)
);


INSERT INTO BUILD (COMP_ID, PART_ID)
VALUES
(300,401),
(301,401),
(304,400),
(303,404),
(302,402);
